version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD: ""
          - MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          - MYSQL_RANDOM_ROOT_PASSWORD: "no"

    working_directory: /tmp/code
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: diaspora-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: RAILS_ENV=production bin/bundle install --jobs $(nproc) --no-deployment --without test development --with postgresql --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: diaspora-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: RAILS_ENV=production bin/rake db:create db:migrate



