version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
      - image: mysql:5.6
        environment:
          - MYSQL_ROOT_PASSWORD: ""
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_RANDOM_ROOT_PASSWORD: no

    working_directory: /tmp/code
    steps:
      - run: echo hello



