version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/ruby:2.3
        environment:
          - PLATFORM: "2.0"
          - RAILS_ENV: "test"
          - S3_BUCKET: "s3://ci-bench2"

      - image: circleci/mysql:5.7
        environment:
          - POSTGRES_PASSWORD: ""

    working_directory: /tmp/code
    steps:
      - checkout

      - run: mkdir /tmp/benchmark

      - run: sudo apt-get -y install awscli

      # Restore bundle cache
      - type: cache-restore
        key: diaspora-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bin/bundle install --jobs $(nproc) --no-deployment --without production development --with mysql --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: diaspora-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run diaspora benchmarking
      - run: bash -c "time -p bin/rake db:create db:migrate" > /tmp/db_migrate.output 2>&1
      - run: cat /tmp/db_migrate.output
      - run: tail -3 /tmp/db_migrate.output | grep real | awk '{printf "%f", $2}' > /tmp/benchmark/db_migrate
      - run: bash -c "time -p BUILD_TYPE=other ./script/ci/build.sh" > /tmp/rspec.output 2>&1
      - run: cat /tmp/rspec.output
      - run: tail -3 /tmp/rspec.output | grep real | awk '{printf "%f", $2}' > /tmp/benchmark/rspec
      - run: cat /tmp/benchmark/*

      # Run ci-bench
      - run: curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash
      - run: sudo apt -y install jq awscli git mysql-workbench sysbench
      - run: git clone https://github.com/kimh/ci-bench.git
      - run: cd ci-bench && ./benchmark.sh $PLATFORM $S3_BUCKET
