version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
        environment:
          - RAILS_ENV: "test"

      - image: notnoopci/postgres@sha256:cda8c36f8187fc3a1685f2aef245cec601720f318d58cc8e2ed25ed1ef6b58f7
        environment:
          - POSTGRES_PASSWORD: ""

    working_directory: /tmp/code
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: diaspora-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bin/bundle install --jobs $(nproc) --no-deployment --without production development --with postgresql --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: diaspora-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      #- run: RAILS_ENV=production bin/rake db:create db:migrate
      - run: BUILD_TYPE=other ./script/ci/build.sh
