version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
      - image: circleci/mysql:5.7

    working_directory: /tmp/code
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: diaspora-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: RAILS_ENV=production bin/bundle install --jobs $(nproc) --no-deployment --without test development --with mysql --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: diaspora-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: RAILS_ENV=production bin/rake db:create db:migrate



