version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
        environment:
          - PLATFORM: "2.0"
          - RAILS_ENV: "test"
          - S3_BUCKET: "s3://ci-bench2"

      - image: notnoopci/postgres@sha256:cda8c36f8187fc3a1685f2aef245cec601720f318d58cc8e2ed25ed1ef6b58f7
        environment:
          - POSTGRES_PASSWORD: ""

    working_directory: /tmp/code
    steps:
      - checkout

      - run: mkdir /tmp/benchmark

      - run: sudo apt-get -y install awscli

      # Restore bundle cache
      - type: cache-restore
        key: diaspora-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bin/bundle install --jobs $(nproc) --no-deployment --without production development --with postgresql --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: diaspora-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bash -c "time -p bin/rake db:create db:migrate" > /tmp/db_migrate.output 2>&1
      - run: cat /tmp/db_migrate.output
      - run: tail -3 /tmp/db_migrate.output | grep real | awk '{printf "%f", $2}' > /tmp/benchmark/db_migrate

      - run: bash -c "time -p BUILD_TYPE=other ./script/ci/build.sh" > /tmp/rspec.output 2>&1
      - run: cat /tmp/rspec.output
      - run: tail -3 /tmp/rspec.output | grep real | awk '{printf "%f", $2}' > /tmp/benchmark/rspec

      - run: cat /tmp/benchmark/*

      - run: ./generate-result.sh > /tmp/benchmark/result_$CIRCLE_BUILD_NUM.json

      - run: aws s3 cp /tmp/benchmark/result_$CIRCLE_BUILD_NUM.json $S3_BUCKET/circleci/$PLATFORM/diaspora/
